### ISSUE TITLE
Found message typo.

### ISSUE THREAD

**Issue by sheo0147** [kaworu/lua-sysctl#11]
Hello. I'm not native English people so sorry for my poor English.

I found maybe TYPO at error message 2 place.

Line 270: 'return (luaL_error(L, "unknown iod '%s'", bufp));'
Line 441: 'return (luaL_error(L, "%s: unknown iod", buf));'

I think "iod" is oid.

Is this right? If so, please fix.
Regards.

**Comment by kaworu** [comment]
Thank you! https://github.com/kaworu/lua-sysctl/commit/f286e4432a20076b512ff6f0cbec78916c3be58a
