### ISSUE TITLE
Any plans to support Lua 5.3 / Lua 5.4?

### ISSUE THREAD

**Issue by kraileth** [kaworu/lua-sysctl#7]
Are there any plans to release a new version of lua-sysctl that supports either Lua 5.3 or even 5.4? Just asking because my ports system of choice (Ravenports) is preparing to remove Lua 5.2 now that 5.4 was released and I'd really like to keep this module available.

**Comment by kAworu** [comment]
Hello @kraileth 

At the moment I don't have enough time to support other versions than the latest FreeBSD with the default Lua version (at this time it means FreeBSD 12.1 and Lua 5.2). I'll leave this issue open to pick it up later (or if someone want to take a look at it).

**Comment by kraileth** [comment]
Thanks for the quick answer! So I'll just hope for the best - maybe FreeBSD will change to a newer version of the Lua interpreter before too long? We have 5.3.5 in base (on -CURRENT) after all and to me it seems like a good idea to change the default version in ports to 5.3, too, before 13.0 is released.

Greetings to Switzerland from another FreeBSD/Awesome user. Appreciate your work!

**Comment by samm-git** [comment]
Basically it works, see https://github.com/kaworu/lua-sysctl/pull/8.
